version: '3.8'

services:
  db:
    image: "mariadb:latest"
    platform: linux/arm64 # Use x86_64 for Windows
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MyR00tMySQLPa$$5w0rD
      MYSQL_DATABASE: MyWordPressDatabaseName
      MYSQL_USER: MyWordpressUser
      MYSQL_PASSWORD: Pa$$5w0rD
    volumes:
      - db_data:/var/lib/mysql
  
  wordpress:
    depends_on:
      - db
    image: "wordpress:latest"
    platform: linux/arm64 # Use x86_64 for Windows
    restart: always
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: MyWordpressUser
      WORDPRESS_DB_PASSWORD: Pa$$5w0rD
      WORDPRESS_DB_NAME: MyWordPressDatabaseName
    volumes:
      - ./wp-content/:/var/www/html/wp-content

  phpmyadmin:
    depends_on:
      - db
    image: "phpmyadmin:latest"
    platform: linux/arm64/v8 # Use x86_64 for Windows
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: MyR00tMySQLPa$$5w0rD
      PMA_PASSWORD: Pa$$5w0rD

volumes:
  db_data:
  wp_data: